spring:
    application:
        name: cmalegrete

    profiles:
        # Active profile (development, produce, test. Default: development)
        active: development

    jpa:
        show-sql: true

    datasource:
        url: jdbc:postgresql://localhost:5432/cmalegrete
        # Add username datasource
        username: 
        # Add password datasource
        password: 

    mail:
        enable: false
        host: smtp.gmail.com
        port: 587
        # Add email username
        username: 
        # Add email password
        password: 
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    
    servlet:
        multipart:
            enabled: true
            max-file-size: 15MB
            max-request-size: 15MB

jwt:
    secret: 1

logs:
    show:
        enable: false
    save:
        enable: false

springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs

app:
  reset-password-url: http://localhost:8080/reset-password